### PR TITLE
Dash deployment

### PR DESCRIPTION
**Pull request by adfi**
Experimented with deploying the app on Heroku following instructions from https://dash.plotly.com/deployment.

Was able to do so with minimal changes, although installing heroku cli required restarts & updates =P.

Looked like you used `pip freeze` on Windows to create the requirements.txt . The deployment server is a Linux box so some of the packages wouldn't install. I've changed it to only include the minimum requirements.

Check out the app on https://scrummy-app.herokuapp.com/

### CODE REVIEW

**Comment by r4ch45** [comment]
Nice one! 👯 🥳 Is there a way we can add assets to the heroku instance (without just uploading them to the repo?)? https://towardsdatascience.com/deploying-your-dash-app-to-heroku-the-magical-guide-39bd6a0c586c - it looks like we have to serve them from elsewhere e.g. whitenoise?

**Comment by adfi** [comment]
Followed the instruction on the blogpost but it's not finding the images (keeps reverting to _noimage.jpg_). So for much for it being painless, will have to check what's on the server.

**Comment by r4ch45** [comment]
hmm it could be due to the update_image_src callback using os.path.exists and failing?
```
    image_path = os.path.join(asset_filepath, f"{current_name}.jpg")
    
    # if the image isn't there then put a static image
    if not os.path.exists(image_path):
        image_path = os.path.join(asset_filepath, "noimage.jpg")
```

**Comment by adfi** [comment]
Trying to fix Whitenoise was a wild goose chase. In the end I messed up the git history fiddling with branches on heroku (not recommended) and it turns out you don't need Whitenoise. Somehow Heroku does recognise the static folder. Obviously this could be a case of "it works on my computer" so feel free to test it.

**Comment by r4ch45** [comment]
Looks good! Thanks!!

**Pull request merged**
